version: '0.0.1.{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.1\mingw73_64

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - g++ --version
  - mingw32-make.exe --version

before_build:
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mingw32-make.exe
  - mkdir package
  - mv release/sakura.exe package
  - cd package
  - windeployqt sakura.exe --qmldir %QTDIR%\qml
  - cd ..
  - 7z -tZip a sakura.zip ./package/* -mx9

deploy:
  release: Sakura-v$(appveyor_build_version)
  description: 'New Release'
  provider: GitHub
  artifact: sakura.zip
  auth_token:
    secure: tT0tHEXbHWmIhS1YY+JPuYATx7uZeZsk9mciX0bchMtFQBx4XHSZmJ3IpFkNFCnU
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: false