version: '0.0.1.{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.1\mingw73_64

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - g++ --version
  - mingw32-make.exe

before_build:
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mingw32-make.exe