version: '0.0.1.{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.1\mingw73_64
    - MINGWDIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - g++ --version
  - mingw32-make.exe --version

before_build:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin;
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mingw32-make.exe
  - ls release
  - mkdir package
  - mv release/sakura.exe package
  - mv sarasa-mono-sc-regular.ttf package
  - cd package
  - windeployqt --qmldir %QTDIR%\qml --release --no-patchqt --libdir ./libs --plugindir ./plugins sakura.exe 
  - cd ..
  - 7z -tZip a sakura.zip ./package/* -mx9

artifacts:
  - path: '*.zip'
    name: sakura-archive

branches:
  only:
    - master
    - /v\d\.\d\.\d/
  except:
    - develop

deploy:
  release: Sakura-v$(appveyor_build_version)
  description: 'A Brand New Version of the Project uh!'
  provider: GitHub
  auth_token:
    secure: tT0tHEXbHWmIhS1YY+JPuYATx7uZeZsk9mciX0bchMtFQBx4XHSZmJ3IpFkNFCnU
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: false