# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    x86_64:
      MSYSTEM: MINGW64
      MSYS2_ARCH: x86_64

steps:
  - script: |
      choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
    displayName: Install MSYS2
  - script: |
      set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
      %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
    displayName: Update MSYS2
  - script: |
      set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-install.sh"
    displayName: Install Depdendencies
    env:
      MSYS2_ARCH: $(MSYS2_ARCH)
      MSYSTEM: $(MSYSTEM)
      CHERE_INVOKING: yes
  - script: |
      set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;%CD:~0,2%\msys64\mingw64\bin
      %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-build.sh"
    displayName: Build
    env:
      MSYS2_ARCH: $(MSYS2_ARCH)
      MSYSTEM: $(MSYSTEM)
      SRC_DIR: $(Build.SourcesDirectory)
      CHERE_INVOKING: yes
  - task: CopyFiles@2
    inputs:
      contents: 'sakura.zip'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: BuildOutput
